---
title: "Temperature dependence of biomass and ecosystem function depend on species interactions. Supplementary File 2: Zooplankton density figures and tables."

output:
  pdf_document: default
  html_document: default

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r load librares, echo=FALSE}

### load libraries
library(MuMIn)
#library(lme4)
#library(plyr)
library(nlme)
library(tidyverse) 
library(broom)
library(reshape2)
library(captioner)
library(knitr)
library(gridExtra)
library(tinytex)
library(cowplot)
```

```{r load data}
data <- read.csv("../data/GarzkeAllwks.csv")
k <- 8.617342*10^-5  # eV/K
xlab <- expression(paste('Temperature (',~degree,'C)',sep=''))
#labels <- c(P = "Algae", PZ = "Algae + Grazers", PZN = "Algae + Grazers + Predators")
```

```{r write functions}
overdisp_fun <- function(model) {
  vpars <- function(m) {
    nrow(m)*(nrow(m)+1)/2
  } 
  model.df <- sum(sapply(VarCorr(model), vpars)) + length(fixef(model))
  rdf <- nrow(model.frame(model))-model.df
  rp <- residuals(model, type = "pearson") # computes pearson residuals
  Pearson.chisq <- sum(rp^2)
  prat <- Pearson.chisq/rdf
  pval <- pchisq(Pearson.chisq, df = rdf, lower.tail = FALSE)
  c(chisq = Pearson.chisq, ratio = prat, rdf = rdf, p = pval)
} 
```

```{r captions}
table_nums <- captioner::captioner(prefix = "Table S2.") #sets prefix for all tables
table_nums(name = "Table_1", caption = "Model selection results for zooplankton abundance, with 1|Tank as a random effect. Model terms are: intercept (Int), Temperature - weekly average (Tw), trophic treatment (TL), Temperature*trophic treatment, statistical estimates", display = FALSE)
table_nums(name = "Table_S3.2", caption = "Daphnia abundance model selection results for Poisson regression. Model terms are: intercept (Int), trophic treatment (TL), Temperature - weekly average (Tw), and statistical estimates", display = FALSE)
table_nums(name = "Table_S3.3", caption = "Daphnia abundance model coefficients", display = FALSE)
table_nums(name = "Table_S3.4", caption = "Copepod abundance model selection results for Poisson regression. Model terms are: intercept (Int), trophic treatment (TL), Temperature - weekly average (Tw), temperature - expt average (Tt), interaction terms and statistical estimates", display = FALSE)
table_nums(name = "Table_S3.5", caption = "Copepod abundance model coefficients", display = FALSE)


fig_nums <- captioner::captioner(prefix = "Figure S3.")
fig_nums(name = "Fig_S3.1", caption = "Abundance of zooplankton (Number / 10L) over all tanks and weeks.", display = FALSE)
fig_nums(name = "Fig_S3.2", caption = "Residual plot for linear model of abundance with normally distributed errors", display = FALSE)
fig_nums(name = "Fig_S3.3", caption = "Residual plot for linear model of abundance with log normally distributed errors", display = FALSE)
fig_nums(name = "Fig_S3.4", caption = "Total Zooplankton abundance and modeled temperature dependence from negative binomial regression", display = FALSE)
fig_nums(name = "Fig_S3.5", caption = "Daphnia abundance with modeled temperature dependence; estimates and confidence intervals given in Table S3.3", display = FALSE)
fig_nums(name = "Fig_S3.6", caption = "Copepod abundance with modeled temperature dependence", display = FALSE)
```

#### Section S3.1: Zooplankton Abundance data over whole experiment
```{r Total Zooplankton analysis, echo = FALSE}
data.N <- as_tibble(data) %>%
  group_by(Tank, trophic.level, week) %>%
  filter(trophic.level != 'P', week > 3) %>%
  dplyr::select(., Tank, trophic.level, week, invTT, average.temp, abundance.Daphnia, abundance.copepods, Daphnia.Copepod.Ratio, total.zoo.abundance.liter) %>%
  arrange(trophic.level, week) 

data.N$Nt <- 10*(data.N$total.zoo.abundance.liter) #b/c we observed ZP in 10 L samples. 
data.N$Dt <- 10*(data.N$abundance.Daphnia)
data.N$Ct <- 10*(data.N$abundance.copepods)
data.N$week <- as.factor(data.N$week)
data.N$Tank <- as.factor(data.N$Tank)

```

`r fig_nums("Fig_S3.1")`

```{r Fig_S3.1: Histogram ZP Abundance, echo=FALSE, fig.width=3, fig.height=3}
hist(data.N$Nt, main = " ")
hist(log(data.N$Nt), main = " ")
```

```{r Testing ZP model options, echo = FALSE}
# first try: poisson regression
#m1 <- glm(Nt ~ trophic.level + invTT, family="poisson", data=data.N)

## second try: lm random effects models with normally distributed errors
#m2 <- lmer(Nt ~ invTT + trophic.level + (1|Tank), data = data.N)
#summary(m2)
#shapiro.test(resid(m2))
```



`r fig_nums("Fig_S3.2")`

```{r resid_plot_lm, echo=FALSE, fig.width=3,fig.height=3}
#qqnorm(resid(m1))
#qqline(resid(m1)) ## ok, shapiro test + this plot show that the linear model is not right.
```

`r fig_nums("Fig_S3.2")`

```{r log density, echo = FALSE, fig.width=3,fig.height=3}
m1 <- lme(log(Nt+1) ~ 1 + I(invTT - mean(invTT))*trophic.level, random = ~ 1|Tank, data = data.N)
qqnorm(resid(m1))
qqline(resid(m1))
```


```{r model comparison log density}
# proceed with alternate fixed effects models
m1a <- lme(log(Nt+1) ~ 1 + trophic.level, random = ~ 1|Tank, data = data.N)
m1b <- lme(log(Nt+1) ~ 1 + I(invTT - mean(invTT)), random = ~ 1|Tank, data = data.N)
m1c <- lme(log(Nt+1) ~ 1, random = ~ 1|Tank, data = data.N)
m1d <- lme(log(Nt+1) ~ 1 + I(invTT - mean(invTT)) + trophic.level, random = ~ 1|Tank, data = data.N)

res <- model.sel(m1, m1a, m1b, m1c, m1d)
#anova(nbinommod1, nbinommod1b) # so proceed wtih nbionmmod1b
``` 

`r table_nums("Table_1")`
```{r Table_S1}
kable(res, digits=2, col.names = c('Int','T~wj~','Z~j~','T~wj~*Z~j~','df', 'logLik', 'AICc', 'd', 'w'))
```

```{r summarize best model}
#summary(nbinommod1b), stdEr is standard error
m.avgN <- model.avg(m1, m1b, m1c, m1a, m1d)
confint(m.avgN) -> ints
coef(m.avgN) -> coefs

NInt.ag <- (fixef(m1)[1])
NInt.agp <- (fixef(m1)[1] + fixef(m1)[3])

Nsl.ag <- fixef(m1)[2]
Nsl.agp <- fixef(m1)[2] + fixef(m1)[4]
```

#april 2019
```{r Fig 4A plotting total zooplankton results, width = 4, height = 4}
### use model coefficients to estimate lines for later plotting; transformation in the negative binomial is log, so exponentiating the estimates reverses that. BUT, in this case we are interested in the response of the log (to get an Ea value) so I will not back transform, but instead plot on logged axes.

N.PZN <- function(x) { NInt.agp + Nsl.agp*(x - mean(x))}
NvalsPZN <- N.PZN(data.N[(data.N$trophic.level=="PZN"),]$invTT - mean(data.N$invTT))

N.PZ <- function(x) { NInt.ag + Nsl.ag*(x - mean(x)) }
NvalsPZ <- N.PZ(data.N[(data.N$trophic.level=="PZ"),]$invTT - mean(data.N$invTT))

data.N$week <- as.numeric(as.character(data.N$week))
# ymin = 0, 

N.plot2 <- ggplot(data = data.N, aes(x = -invTT, y = log(Nt+1), xmin = -40, xmax = -38.5, group = week, shape = as.factor(trophic.level), alpha = week)) +
  theme_bw() +
  geom_point(aes(group = as.character(week))) +
  theme(panel.grid.minor = element_blank(), 
        panel.grid.major = element_blank(),  
        legend.position = c(.9,.7),
        #legend.justification = c(.5,0),
        strip.text.y = element_blank(),
        strip.background = element_rect(colour="white", fill="white")) +
  scale_alpha("Week") +
  scale_shape_manual(guide = "none", values = c(16,17)) +
  ylab("Zooplankton abundance ln(ind/10L)") + 
  scale_x_continuous("Temperature (1/kTi)", sec.axis =sec_axis(~((1/(k*-.))-273), name = xlab))

Fig4A <- N.plot2 +
  geom_smooth(data = subset(data.N, trophic.level == "PZN"), aes(x = -invTT, y = N.PZN(invTT)), method = "lm", se = FALSE, inherit.aes = FALSE, formula = y ~ x, color = 'gray', size = 1.5, lty = 2) +
 geom_smooth(data = subset(data.N, trophic.level == "PZ"), aes(x = -invTT, y = N.PZ(invTT)), method = "lm", se = FALSE, inherit.aes = FALSE, formula = y ~ x, color = 1, size = 1.5, lty = 1)


#ggsave("Fig4.png", width = 4, height = 4)
```

```{r plotting total zooplankton results}
### use model coefficients to estimate lines for later plotting; transformation in the negative binomial is log, so exponentiating the estimates reverses that. BUT, in this case we are interested in the response of the log (to get an Ea value) so I will not back transform, but instead plot on logged axes.

data.N$week <- as.numeric(as.character(data.N$week))

N.plot2 <- ggplot(data = data.N, aes(x = -invTT, y = Nt, xmin = -40, xmax = -38.5, group = week, shape = as.factor(trophic.level), alpha = week)) +
  theme_bw() +
  geom_point(aes(group = as.character(week))) +
  theme(panel.grid.minor = element_blank(), 
        panel.grid.major = element_blank(),  
        legend.text = element_text(size = 6), 
        legend.title = element_text(size = 7), 
        legend.key = element_rect(fill = NA), 
        strip.text.y = element_blank(),
        strip.background = element_rect(colour="white", fill="white")) +
  #scale_alpha("week", guide = "none") +
  scale_shape_manual(guide = guide_legend(title = "Trophic Treatment"), values = c(1,2,22,23,8,15,16,17)) +
  ylab("Zooplankton abundance (ind/10L)") + 
  scale_x_continuous("Temperature (1/kTi)", sec.axis =sec_axis(~((1/(k*-.))-273), name = xlab))

N.plot3 <- N.plot2 +
  geom_smooth(data = subset(data.N, trophic.level == "PZ"), aes(x = -invTT, y = N.PZ(invTT)), method = "lm", se = FALSE, inherit.aes = FALSE, formula = y ~ x, color = 'black', size = 1.5) +
  geom_smooth(data = subset(data.N, trophic.level == "PZN"), aes(x = -invTT, y = N.PZ(invTT)), method = "lm", se = FALSE, inherit.aes = FALSE, formula = y ~ x, color = 'gray', size = 1.5, lty = 2) #+
  #geom_ribbon(data = subset(data.N, trophic.level == "PZ"), aes(ymin = N.PZL(invTT), ymax = N.PZU(invTT)), fill = "blue", alpha = .25)

ggsave("Fig4.png", width = 4, height = 4)
```

`r fig_nums("Fig_S3.4")`

```{r N_plot, fig.width=4,fig.height=4}
N.plot3
```

####
####
####


### Section S3.2: Daphnia and Copepods
`r fig_nums("Fig_S3.4")`

```{r Daphnia_abundance, fig.width=3,fig.height=3}
hist(data.N$Dt, main = "Daphnia / 10L")
hist(data.N$Dt, main = "Copepods / 10L")
#hist(data.N$Daphnia.Copepod.Ratio)
```

```{r log Daphnia density, echo = FALSE}
D1 <- lme(log(abundance.Daphnia+1) ~ 1 + I(invTT - mean(invTT))*trophic.level, random = ~ 1|Tank, data = data.N)
qqnorm(resid(D1))
# proceed with alternate fixed effects models
D1a <- lme(log(abundance.Daphnia+1) ~ 1 + trophic.level, random = ~ 1|Tank, data = data.N)
D1b <- lme(log(abundance.Daphnia+1) ~ 1 + I(invTT - mean(invTT)), random = ~ 1|Tank, data = data.N)
D1c <- lme(log(abundance.Daphnia+1) ~ 1, random = ~ 1|Tank, data = data.N)
D1d <- lme(log(abundance.Daphnia+1) ~ 1 + I(invTT - mean(invTT)) + trophic.level, random = ~ 1|Tank, data = data.N)

resD <- model.sel(D1, D1a, D1b, D1c, D1d)
```

`r table_nums("Table_S3.2")`
```{r Daphnia table}
kable(resD, digits=2, col.names = c('Int','T~wj~','Z~j~','T~wj~*Z~j~','df', 'logLik', 'AICc', 'd', 'w'))
```


`r table_nums("Table_S3.3")`
```{r Table S3.3: Daphnia coefs and confints}
kable(D.est, digits=2)
```



```{r Daphnia predicted values}
### use model coefficients to estimate lines for later plotting
D.PZ <- function(x) { (fixef(m1Da)[1]) } # for trophic level 3
D.PZN <- function(x) { (fixef(m1Da)[1] + fixef(m1Da)[2]) } # for trophic level 3
```

```{r Fig 4B Daphnia plots, width = 4, height = 4}
D.plot2 <- ggplot(data = data.N, aes(x = -invTT, y = log(abundance.Daphnia+1), xmin = -40, xmax = -38.5, group = week, shape = as.factor(trophic.level), alpha = week)) +
  theme_bw() +
  theme(legend.position = "none")+
  geom_point(aes(group = as.character(week)), guide = "none") +
  theme(panel.grid.minor = element_blank(), 
        panel.grid.major = element_blank(),  
        #legend.text = element_text(size = 6), 
        #legend.title = element_text(size = 7), 
        #legend.key = element_rect(fill = NA), 
        strip.text.y = element_blank(),
        strip.background = element_rect(colour="white", fill="white")) +
  scale_alpha("Week") +
  scale_shape_manual(guide = "none", values = c(16,17)) +
  ylab("Daphnia density ln(ind/10L)") + 
  scale_x_continuous("Temperature (1/kTi)", sec.axis =sec_axis(~((1/(k*-.))-273), name = xlab))

#, values = c(1,2,22,23,8,15,16,17)

Fig4B <- D.plot2 +
  geom_smooth(data = subset(data.N, trophic.level == "PZ"), aes(x = -invTT, y = D.PZ(invTT)), method = "lm", se = FALSE, inherit.aes = FALSE, formula = y ~ x, color = 'black', size = 1.5) +
  geom_smooth(data = subset(data.N, trophic.level == "PZN"), aes(x = -invTT, y = D.PZN(invTT)), method = "lm", se = FALSE, inherit.aes = FALSE, formula = y ~ x, color = 'gray', size = 1.5, lty = 1)

#D.plot2 + geom_line(data=transform(data.N, abundance.Daphnia=(predict(poismod.Db))))

#ggsave("Fig4a.png", width = 4, height = 4)
```

`r fig_nums("Fig_S3.5")`

```{r Fig_S3.5: Daphnia abundance plot, fig.width=4,fig.height=4}
D.plot3
```





```{r log Copepod density, echo = FALSE}
m1C <- lme(log(Ct+1) ~ 1 + I(invTT - mean(invTT))*trophic.level, random = ~ 1|Tank, data = data.N)
qqnorm(resid(m1C))
# proceed with alternate fixed effects models
m1Ca <- lme(log(Ct+1) ~ 1 + trophic.level, random = ~ 1|Tank, data = data.N)
m1Cb <- lme(log(Ct+1) ~ 1 + I(invTT - mean(invTT)), random = ~ 1|Tank, data = data.N)
m1Cc <- lme(log(Ct+1) ~ 1, random = ~ 1|Tank, data = data.N)
m1Cd <- lme(log(Ct+1) ~ 1 + I(invTT - mean(invTT)) + trophic.level, random = ~ 1|Tank, data = data.N)

resC <- model.sel(m1C, m1Ca, m1Cb, m1Cc, m1Cd)
```

`r table_nums("Table_S3.4")`

```{r Copepod abundance results}
kable(resC, digits=2, col.names = c('Int','T~wj~','Z~j~','T~wj~*Z~j~','df', 'logLik', 'AICc', 'd', 'w'))
```

```{r Copepod abundance model coefs}
#m1C <- poismod.Cc
#C.est <- cbind(Estimate = coef(m1C), se = stdEr(m1C), 
           # "Pr(>|z|)" = 2 * pnorm(abs(coef(m1C)/stdEr(m1C)), lower.tail=FALSE),
          #  LL = coef(m1C) - 1.96 * stdEr(m1C),
           # UL = coef(m1C) + 1.96 * stdEr(m1C))
```


`r table_nums("Table_S3.5")`
```{r Table_S3.5}
kable(C.est, digits = 2)
```


```{r Copepod plots, width = 4, height = 4}
### use model coefficients to estimate lines for later plotting
C.PZ <- function(x) { (fixef(m1Cb)[1] + fixef(m1Cb)[2]*x) } # for trophic level 3
Cvals <- C.PZ(data.N$invTT - mean(data.N$invTT))

#data.N$Chat <- predict(poismod.Cc)

C.plot2 <- ggplot(data = data.N, aes(x = -invTT, y = log(Ct + 1), xmin = -40, xmax = -38.5, group = week, shape = as.factor(trophic.level), alpha = week)) +
  theme_bw() +
  theme(legend.position = "none") +
  geom_point(aes(group = as.character(week))) +
  theme(panel.grid.minor = element_blank(), 
        panel.grid.major = element_blank(),  
        #legend.text = element_text(size = 6), 
        #legend.title = element_text(size = 7), 
        #legend.key = element_rect(fill = NA), 
        strip.text.y = element_blank(),
        strip.background = element_rect(colour="white", fill="white")) +
  scale_alpha("week") +
  scale_shape_manual(guide = "none", values = c(16,17)) +
  ylab("Copepod density ln(ind/10L)") + 
  scale_x_continuous("Temperature (1/kTi)", sec.axis =sec_axis(~((1/(k*-.))-273), name = xlab))


Fig4C <- C.plot2 +
  geom_smooth(data = data.N, aes(x = -invTT, y = Cvals), method = "lm", se = FALSE, inherit.aes = FALSE, formula = y ~ x, color = 'black', size = 1.5)

#ggsave("Fig4b.png", width = 4, height = 4)
```



```{r Figure 4 main text, fig.width=4, fig.height=12, echo = FALSE}

tiff(file = "Fig4.tiff", width = 10, height = 30, units = "cm", res = 300, pointsize = 6)

Fig4MT <- plot_grid(Fig4A, Fig4B, Fig4C, labels = c("A", "B", "C"), ncol = 1, align = "v")
Fig4MT

dev.off()
#ggsave("Fig4.tiff", plot = Fig4MT, device = "tiff", path = "../figures/", width = 8, height = 4)
```


